shared: &shared
  adapter: postgresql
  encoding: utf8
  username: <%= ENV["USER"] || "postgres" %>

development:
  <<: *shared
  database: whimsy_space_development

test:
  <<: *shared
  database: whimsy_space_test
  min_messages: WARNING

production:
  <<: *shared
  database: whimsy_space_production
